#! /bin/csh

# -----------------------  check for valid argument ....

if ( $1 == "" ) then
  echo "Usage MakeBook <valid_PS_file_name>"
  exit(-1)
endif

set psfile=`echo $1`


if ( -e $psfile ) then
  echo $psfile | awk '{ printf "Processing \"%s\" ...\n",$1}'

#  ----------------------- check for postscript format ...

  set psflag=`head -1 $psfile | awk '{ if(substr($1,3,9)=="PS-Adobe-") print "1"; else print "0";}'`
  if ( $psflag == 0 ) then
    echo $psfile | awk '{ printf "Error: input file \"%s\" is not a PostScript file!\n",$1}'
    exit(-1)
  endif

  awk 'BEGIN {o=1; n=1; i=3; p=1} \
       { lineout=$0; \
         if($1=="%%Page:") \
         { o=0; \
           if(n==$2) \
           { o=1; n+=i; i=(i+2)%4; \
             if(i==1) { printf "%%%%Page: %d %d\n",p,p; p++; lineout="0.707 0.707 scale 90 rotate 598 -840 translate gsave"} \
             if(i==3) { lineout="grestore -594 0 translate gsave"} \
           } \
         } \
         if(($1=="showpage")&&(i==1)) lineout=""; \
         if($0=="%%EOF") o=0; \
         if(o==1) print lineout; \
       } \
       END { if(i==1) print "grestore showpage"; print "%%EOF" }' $psfile >! ${psfile}.0
         
  awk 'BEGIN {o=1; n=2; i=1; p=1} \
       { lineout=$0; \
         if($1=="%%Page:") \
         { o=0; \
           if(n==$2) \
           { o=1; n+=i; i=(i+2)%4; \
             if(i==3) { printf "%%%%Page: %d %d\n",p,p; p++; lineout="0.707 0.707 scale 90 rotate 0 -840 translate gsave"} \
             if(i==1) { lineout="grestore 590 0 translate gsave"} \
           } \
         } \
         if(($1=="showpage")&&(i==3)) lineout=""; \
         if($0=="%%EOF") o=0; \
         if(o==1) print lineout; \
       } \
       END { if(i==3) print "grestore showpage"; print "%%EOF" }' $psfile >! ${psfile}.1

  else
  echo $psfile | awk '{ printf "Error: could not find file \"%s\"\n",$1}'
endif
